version: 2
jobs:
  build-image:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build image
          command: |
            set -ev
            ./pipe_build_up_test.sh
      - run:
          name: publish image on dockerhub
          command: |
            set -ev
            readonly image=cyberdojo/exercises
            docker tag  ${image}:latest ${image}:${CIRCLE_SHA1:0:7}
            docker tag  ${image}:latest ${image}:beta
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            docker push ${image}:${CIRCLE_SHA1:0:7}
            docker push ${image}:beta
            docker push ${image}:latest

  deploy-image-to-beta:
    docker:
      - image: cyberdojo/gcloud-kubectl-helm
    steps:
      - run:
          name: authenticate with gcloud and deploy with helm
          command: |
            set -e
            echo $GCP_K8S_CREDENTIALS > /gcp/gcp-credentials.json
            gcloud auth activate-service-account "$SERVICE_ACCOUNT" --key-file=/gcp/gcp-credentials.json
            gcloud container clusters get-credentials "$CLUSTER" --zone "$ZONE" --project "$PROJECT"
            helm init --client-only
            helm repo add praqma https://praqma-helm-repo.s3.amazonaws.com/
            # comment this to reset _all_ services
            export HELM_REUSE_VALUES=--reuse-values
            helm upgrade --install --version 0.1.0 ${HELM_REUSE_VALUES} --namespace=beta --set-string image.exercises.tag=${CIRCLE_SHA1:0:7} beta-cyber-dojo praqma/cyber-dojo


workflows:
  version: 2
  build:
    jobs:
      - build-image:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
      - deploy-image-to-beta:
          context: cyberdojo-context
          requires:
            - build-image
