
fullnameOverride: "exercises"

replicaCount: 3

service:
  port: 4525
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4525"

volumes:
  - name: exercises-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "16Mi"

containers:
  - name: exercises
    image: cyberdojo/exercises
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: exercises-tmp-dir
        mountPath: /tmp
        readOnly: false
    resources:
      limits:
        memory: 32Mi
      requests:
        memory: 32Mi
    livenessProbe:
      path: /alive?
      port: 4525
    readinessProbe:
      path: /ready?
      port: 4525

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
