# Default values for cyber-dojo-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "exercises"

replicaCount: 1

service:
  port: 4525

volumes:
  - name: exercises-tmp-dir
    emptyDir: {}

containers:
  - name: exercises
    image: cyberdojo/exercises
    tag: ""
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: exercises-tmp-dir
        mountPath: /tmp
        readOnly: false
    resources:
      limits:
        memory: 32Mi
      requests:
        memory: 32Mi
      livenessProbe:
        path: /sha
        port: 4525
      readinessProbe:
        path: /ready?
        port: 4525

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
