
fullnameOverride: "exercises"

replicaCount: 3

service:
  port: 4999
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4999"

volumes:
  - name: exercises-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "16Mi"

podSecurityContext:
  runAsUser: 65534 # nobody
  fsGroup: 65534 # nobody

containers:
  - name: exercises
    image: cyberdojo/exercises
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: exercises-tmp-dir
        mountPath: /tmp
        readOnly: false
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi
    livenessProbe:
      path: /alive?
      port: 4999
    readinessProbe:
      path: /ready?
      port: 4999

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
